**Load dataset**

In [1]:
from assignments.helpers import preprocess_data
preprocessed_data = preprocess_data()

In [2]:
preprocessed_data

,LotArea,LotConfig,Neighborhood,BldgType,OverallQual,YearBuilt,MasVnrArea,BsmtExposure,BsmtFinType1,TotalBsmtSF,HeatingQC,CentralAir,GrLivArea,FullBath,Fireplaces,FireplaceQu,GarageFinish,GarageCars,SaleCondition,SalePrice
0,8450,Inside,CollgCr,1Fam,7,2003,196.0,No,GLQ,856,Ex,Y,1710,2,0,NaN,RFn,2,Normal,208500
1,9600,FR2,Veenker,1Fam,6,1976,0.0,Gd,ALQ,1262,Ex,Y,1262,2,1,TA,RFn,2,Normal,181500
2,11250,Inside,CollgCr,1Fam,7,2001,162.0,Mn,GLQ,920,Ex,Y,1786,2,1,TA,RFn,2,Normal,223500
3,9550,Corner,Crawfor,1Fam,7,1915,0.0,No,ALQ,756,Gd,Y,1717,1,1,Gd,Unf,3,Abnorml,140000
4,14260,FR2,NoRidge,1Fam,8,2000,350.0,Av,GLQ,1145,Ex,Y,2198,2,1,TA,RFn,3,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,7917,Inside,Gilbert,1Fam,6,1999,0.0,No,Unf,953,Ex,Y,1647,2,1,TA,RFn,2,Normal,175000
1456,13175,Inside,NWAmes,1Fam,6,1978,119.0,No,ALQ,1542,TA,Y,2073,2,2,TA,Unf,2,Normal,210000
1457,9042,Inside,Crawfor,1Fam,7,1941,0.0,No,GLQ,1152,Ex,Y,2340,2,2,Gd,RFn,1,Normal,266500
1458,9717,Inside,NAmes,1Fam,5,1950,0.0,Mn,GLQ,1078,Gd,Y,1078,1,0,NaN,Unf,1,Normal,142125
1459,9937,Inside,Edwards,1Fam,5,1965,0.0,No,BLQ,1256,Gd,Y,1256,1,0,NaN,Fin,1,Normal,147500

In [3]:
preprocessed_data.columns

Index(['LotArea', 'LotConfig', 'Neighborhood', 'BldgType', 'OverallQual',
       'YearBuilt', 'MasVnrArea', 'BsmtExposure', 'BsmtFinType1',
       'TotalBsmtSF', 'HeatingQC', 'CentralAir', 'GrLivArea', 'FullBath',
       'Fireplaces', 'FireplaceQu', 'GarageFinish', 'GarageCars',
       'SaleCondition', 'SalePrice'],
      dtype='str')

In [4]:
preprocessed_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1460 non-null   int64
 1   LotConfig      1460 non-null   str
 2   Neighborhood   1460 non-null   str
 3   BldgType       1460 non-null   str
 4   OverallQual    1460 non-null   int64
 5   YearBuilt      1460 non-null   int64
 6   MasVnrArea     1452 non-null   float64
 7   BsmtExposure   1422 non-null   str
 8   BsmtFinType1   1423 non-null   str
 9   TotalBsmtSF    1460 non-null   int64
 10  HeatingQC      1460 non-null   str
 11  CentralAir     1460 non-null   str
 12  GrLivArea      1460 non-null   int64
 13  FullBath       1460 non-null   int64
 14  Fireplaces     1460 non-null   int64
 15  FireplaceQu    770 non-null    str
 16  GarageFinish   1379 non-null   str
 17  GarageCars     1460 non-null   int64
 18  SaleCondition  1460 non-null   str
 19  SalePrice      1460 non-null   int64
dtypes: float64(1), int64(9), str(10)
memory usage: 228.3 KB

In [5]:
preprocessed_data.describe()

,LotArea,OverallQual,YearBuilt,MasVnrArea,TotalBsmtSF,GrLivArea,FullBath,Fireplaces,GarageCars,SalePrice
count,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,10516.828082,6.099315,1971.267808,103.685262,1057.429452,1515.463699,1.565068,0.613014,1.767123,180921.195890
std,9981.264932,1.382997,30.202904,181.066207,438.705324,525.480383,0.550916,0.644666,0.747315,79442.502883
min,1300.000000,1.000000,1872.000000,0.000000,0.000000,334.000000,0.000000,0.000000,0.000000,34900.000000
25%,7553.500000,5.000000,1954.000000,0.000000,795.750000,1129.500000,1.000000,0.000000,1.000000,129975.000000
50%,9478.500000,6.000000,1973.000000,0.000000,991.500000,1464.000000,2.000000,1.000000,2.000000,163000.000000
75%,11601.500000,7.000000,2000.000000,166.000000,1298.250000,1776.750000,2.000000,1.000000,2.000000,214000.000000
max,215245.000000,10.000000,2010.000000,1600.000000,6110.000000,5642.000000,3.000000,3.000000,4.000000,755000.000000

In [6]:
preprocessed_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   LotArea        1460 non-null   int64
 1   LotConfig      1460 non-null   str
 2   Neighborhood   1460 non-null   str
 3   BldgType       1460 non-null   str
 4   OverallQual    1460 non-null   int64
 5   YearBuilt      1460 non-null   int64
 6   MasVnrArea     1452 non-null   float64
 7   BsmtExposure   1422 non-null   str
 8   BsmtFinType1   1423 non-null   str
 9   TotalBsmtSF    1460 non-null   int64
 10  HeatingQC      1460 non-null   str
 11  CentralAir     1460 non-null   str
 12  GrLivArea      1460 non-null   int64
 13  FullBath       1460 non-null   int64
 14  Fireplaces     1460 non-null   int64
 15  FireplaceQu    770 non-null    str
 16  GarageFinish   1379 non-null   str
 17  GarageCars     1460 non-null   int64
 18  SaleCondition  1460 non-null   str
 19  SalePrice      1460 non-null   int64
dtypes: float64(1), int64(9), str(10)
memory usage: 228.3 KB

In [7]:
preprocessed_data.isnull().sum()

LotArea            0
LotConfig          0
Neighborhood       0
BldgType           0
OverallQual        0
YearBuilt          0
MasVnrArea         8
BsmtExposure      38
BsmtFinType1      37
TotalBsmtSF        0
HeatingQC          0
CentralAir         0
GrLivArea          0
FullBath           0
Fireplaces         0
FireplaceQu      690
GarageFinish      81
GarageCars         0
SaleCondition      0
SalePrice          0
dtype: int64